### ISSUE TITLE
video doesn't load inside Panel

### ISSUE THREAD

**Issue by laleikeCO** [HashandSalt/kirby3-video#1]
I've try to use your tag inside of the panel in the https://github.com/mgfagency/kirby-helpsection Plugin. It points to the video in the media/ folder but the video doesn't appears there.

is there a way to point to the original video in the content folder?

**Comment by HashandSalt** [comment]
I think this is actually a potential problem with helpsection plugin. I could not get videos to work myself, I think even without my plugin. I ended up using animated gifs to get around it.
