### ISSUE TITLE
Videourl not being addressed right

### ISSUE THREAD

**Issue by eWalthert** [HashandSalt/kirby3-video#2]
Dear HashandSalt,
As reported in the Kirby forum, the plugin does not pick the specified video-file but whatever is the alphabetically first file on the page. (that can even be a .png file).
We can work around this, by adding a zero in front of the videos file-name.
It does not work when more than one video is supposed to be displayed on one page.
The plugin will aways pick the first file.

I had a look into the plugin but was not able to locate the error.

**Comment by HashandSalt** [comment]
As per the readme...

> The plugin makes use of ->file() - be aware that this uses the first image or first video on the page if the desired one is not found. This is by design.

**Comment by HashandSalt** [comment]
Fixed in 0.0.6
