### ISSUE TITLE
Several template issues

### ISSUE THREAD

**Issue by distantnative** [HashandSalt/kirby3-video#5]
Getting a few template errors in the console

<img width="495" alt="Screenshot 2023-05-29 at 15 21 32" src="https://github.com/HashandSalt/kirby3-video/assets/3788865/4bd80156-6cca-47ed-a29b-473e86a327f8">
<img width="432" alt="Screenshot 2023-05-29 at 15 21 40" src="https://github.com/HashandSalt/kirby3-video/assets/3788865/89f1c68c-d0be-44d0-8cf1-bcf1495b5e43">

**Comment by HashandSalt** [comment]
Thanks @distantnative all fixed.
